name: PublishVersion

on:
  workflow_dispatch:
    inputs:
      versionnum:
        description: '5 digit version Number e.g. 00099 or AZaz-_09'
        required: true


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Build
      run: |       
        perl -p -i -e 's/v\/latest/v\/${{inputs.versionnum}}/' package.json
        grep homepage package.json
        npm install
        npm run build
        date > build/builddate.txt
        git rev-parse --short HEAD > build/commit.txt
      
    - name: Deploy to Production
      if: github.ref == 'refs/heads/master'
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        ls -la
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${DEPLOY_KEY}"
        git clone git@github.com:scribear/v.git
        git config --global user.email "angrave@illinois.edu"
        git config --global user.name "scribear-bot"
        cd v
        ls -la
        export SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`
        
        
        mkdir -p "${{ inputs.versionnum }}"
        mv ../build/* "${{ inputs.versionnum }}"
        git add "${{ inputs.versionnum }}"

        git commit -m "Commit Deploy: ${SHORT_SHA} to ${{ inputs.versionnum }}"
        git push origin master
